version: '2'
catalog:
  name: "nginx"
  version: "v0.0.1"
  description: "A web service."
  minimum_rancher_version: v0.51.0
  questions:
    - variable: http_port
      description: "http port to access nginx"
      label: "Http Port"
      required: true
      default: "9999" 
      type: "int"
    - variable: "volume_driver"
      description: "Volume driver to associate with this service"
      label: "Volume Driver"
      required: true
      default: "local"
      type: enum
      options: # List of options if using type of `enum`
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
    - variable: "db_link"
      description: |
        DB external service link cluster.
      label: "External db service"
      default: ""
      required: false
      type: "service"
    - variable: mysql_db
      description: "mysql db"
      label: "Mysql db"
      required: true
      default: "nginx"
      type: "string"
    - variable: mysql_user
      description: "mysql user"
      label: "Mysql User"
      required: true
      default: "nginx"
      type: "string"
    - variable: mysql_password
      description: "mysql root password"
      label: "Mysql Password"
      required: true
      default: "000000"
      type: "password"
services:
  nginx:
    scale: 1
    retain_ip: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 300000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 120000
